[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "opendxa"
version = "1.0.0"
description = "Open Source Dislocation Extraction Algorithm (DXA)"
readme = "README.md"
requires-python = ">=3.7"
authors = [
    { name = "Rodolfo Herrera Hernandez", email = "contact@rodyherrera.com" }
]

license = { file = "LICENSE" }
dependencies = [
    "numpy",
    "numba",
    "cupy-cuda12x",
    "matplotlib"
]

[project.urls]
Homepage = "https://github.com/yourusername/opendxa"
